#include <string>
#include <vector>
#include <TTree.h>
#include <TLorentzVector.h>

class EventInfoTree {
  public:
    int    countEvents ;
    int    runno ;
    int    lumisec ;
    int    evtno;
    int    npv;   
    int    npuTrue;
    int    puBX;
    int    npuInt;
    int    nGoodVtx;
    std::vector<int>   ndofVtx;
    std::vector<float> chi2Vtx;
    std::vector<float> zVtx;
    std::vector<float> rhoVtx;
    std::vector<float> etaVtx;
    std::vector<float> phiVtx;
    

    int    nSV;
    int    nGoodSV;
    std::vector<float> ptSV;
    std::vector<float> etaSV;
    std::vector<float> phiSV;
    std::vector<float> energySV;
    std::vector<float> massSV;
    std::vector<int>   isMatchedToJetSV;
    std::vector<float> dRFlightJetSV;
    std::vector<float> dRJetSV; 
    std::vector<float> chi2SV;
    std::vector<float> normChi2SV;
    std::vector<float> dxySV;
    std::vector<float> dxyerrSV;
    std::vector<float> dxysigSV;
    std::vector<float> d3dSV;
    std::vector<float> d3derrSV;
    std::vector<float> d3dsigSV;
    std::vector<float> costhetaSvPvSV;
    std::vector<int>   ntrkSV;
    std::vector<int>   ndauSV;
    std::vector<int>   ndofSV;
    std::vector<int>   isSVgen;
    std::vector<int>   isSVb;
    std::vector<int>   isSVc;
    std::vector<int>   isSVl;
    std::vector<int>   isSVo;
    std::vector<int>   isSVbg;
    std::vector<int>   isSVcg;
    std::vector<int>   nbsSV;
    std::vector<int>   ncsSV;
    std::vector<int>   nlsSV;
    std::vector<int>   ngsSV;
    std::vector<int>   nothersSV;
    std::vector<int>   isMatchedtoGenSV;  
    std::vector<int>   matchedGenIsHardProcess;
    std::vector<int>   matchedGenIsLastCopyBeforeFSR;
    std::vector<float> matchedGenPtSV;
    std::vector<float> matchedGenEtaSV;
    std::vector<float> matchedGenMassSV;
    std::vector<float> matchedGenPhiSV;
    std::vector<float> matchedGenEnergySV;
    std::vector<int>   matchedGenMomSV;
    std::vector<float> matchedGenMindRSV;
    std::vector<float> matchedGendRSV;
    std::vector<float> trkDeltaRSV;
    std::vector<float> trkPtRelSV;
    std::vector<float> trkEtaSV;
    std::vector<float> trkEtaRelSV;
    std::vector<float> trkPParSV;
    std::vector<float> trkPtRatioSV;  
    std::vector<float> trkPParRatioSV;   
    std::vector<float> trkSip2dValSV;
    std::vector<float> trkSip2dSigSV;
    std::vector<float> trkSip3dValSV;
    std::vector<float> trkSip3dSigSV;
    std::vector<float> trkSVDistValSV;
    std::vector<float> trkSVDistSigSV;
     
    void clearTreeVectors() {
       ndofVtx.clear();
       chi2Vtx.clear();
       zVtx.clear();
       rhoVtx.clear();
       etaVtx.clear();
       phiVtx.clear();
       
       ptSV.clear();
       etaSV.clear();
       phiSV.clear();
       energySV.clear();
       massSV.clear();
       isMatchedToJetSV.clear();
       dRFlightJetSV.clear();
       dRJetSV.clear(); 
       chi2SV.clear();
       normChi2SV.clear();
       dxySV.clear();
       dxyerrSV.clear();
       dxysigSV.clear();
       d3dSV.clear();
       d3derrSV.clear();
       d3dsigSV.clear();       
       costhetaSvPvSV.clear();
       ntrkSV.clear();
       ndauSV.clear();
       ndofSV.clear();
       isSVgen.clear();
       isSVb.clear();
       isSVc.clear();
       isSVl.clear();
       isSVbg.clear();
       isSVcg.clear();
       isSVo.clear();
       nbsSV.clear();
       ncsSV.clear();
       nlsSV.clear();
       ngsSV.clear();
       nothersSV.clear();
       isMatchedtoGenSV.clear();
       matchedGenIsLastCopyBeforeFSR.clear();
       matchedGenIsHardProcess.clear();
       matchedGenPtSV.clear();
       matchedGenEtaSV.clear();
       matchedGenMassSV.clear();
       matchedGenPhiSV.clear();
       matchedGenMomSV.clear();
       matchedGenMindRSV.clear();
       matchedGenEnergySV.clear();
       matchedGendRSV.clear();
       trkDeltaRSV.clear();
       trkPtRelSV.clear();
       trkEtaSV.clear();
       trkEtaRelSV.clear();
       trkPParSV.clear();
       trkPtRatioSV.clear();
       trkPParRatioSV.clear();
       trkSip2dValSV.clear();
       trkSip2dSigSV.clear();
       trkSip3dValSV.clear();
       trkSip3dSigSV.clear();
       trkSVDistValSV.clear();
       trkSVDistSigSV.clear();
    }

    void RegisterTree(TTree* tree, std::string name="Evts") {
      tree->Branch((name+"_countEvents").c_str(), &countEvents, (name+"_countEvents/I").c_str());
      tree->Branch((name+"_runno").c_str(),   &runno,    (name+"_runno/I").c_str());
      tree->Branch((name+"_lumisec").c_str(), &lumisec,  (name+"_lumisec/I").c_str());
      tree->Branch((name+"_evtno").c_str(),   &evtno,    (name+"_evtno/I").c_str());
      tree->Branch((name+"_npv").c_str(),     &npv,      (name+"_npv/I").c_str());
      tree->Branch((name+"_npuTrue").c_str(), &npuTrue,  (name+"_npuTrue/I").c_str());
      tree->Branch((name+"_puBX").c_str(),    &puBX,     (name+"_puBX/I").c_str());
      tree->Branch((name+"_npuInt").c_str(),  &npuInt,   (name+"_npuInt/I").c_str());      
      tree->Branch((name+"_nGoodVtx").c_str(),&nGoodVtx, (name+"_nGoodVtx/I").c_str());
      tree->Branch((name+"_ndofVtx").c_str(), &ndofVtx);
      tree->Branch((name+"_chi2Vtx").c_str(), &chi2Vtx);
      tree->Branch((name+"_zVtx").c_str(),    &zVtx);
      tree->Branch((name+"_rhoVtx").c_str(),  &rhoVtx); 
      tree->Branch((name+"_etaVtx").c_str(),  &etaVtx);
      tree->Branch((name+"_phiVtx").c_str(),  &phiVtx);
      
      tree->Branch((name+"_nSV").c_str(),             &nSV,      (name+"_nSV/I").c_str());
      tree->Branch((name+"_nGoodSV").c_str(),         &nGoodSV,  (name+"_nGoodSV/I").c_str());
      tree->Branch((name+"_ptSV").c_str(),            &ptSV);
      tree->Branch((name+"_etaSV").c_str(),           &etaSV);
      tree->Branch((name+"_phiSV").c_str(),           &phiSV);
      tree->Branch((name+"_energySV").c_str(),        &energySV);
      tree->Branch((name+"_massSV").c_str(),          &massSV);
      tree->Branch((name+"_isMatchedToJetSV").c_str(),&isMatchedToJetSV);
      tree->Branch((name+"_dRFlightJetSV").c_str(),   &dRFlightJetSV);
      tree->Branch((name+"_dRJetSV").c_str(),         &dRJetSV);
      tree->Branch((name+"_chi2SV").c_str(),          &chi2SV); 
      tree->Branch((name+"_normChi2SV").c_str(),      &normChi2SV);
      tree->Branch((name+"_dxySV").c_str(),           &dxySV); 
      tree->Branch((name+"_dxyerrSV").c_str(),        &dxyerrSV); 
      tree->Branch((name+"_dxysigSV").c_str(),        &dxysigSV);
      tree->Branch((name+"_d3dSV").c_str(),           &d3dSV); 
      tree->Branch((name+"_d3derrSV").c_str(),        &d3derrSV); 
      tree->Branch((name+"_d3dsigSV").c_str(),        &d3dsigSV);
      tree->Branch((name+"_costhetaSvPvSV").c_str(),  &costhetaSvPvSV); 
      tree->Branch((name+"_ntrkSV").c_str(),          &ntrkSV);
      tree->Branch((name+"_ndauSV").c_str(),          &ndauSV);
      tree->Branch((name+"_ndofSV").c_str(),          &ndofSV);
      tree->Branch((name+"_isSVgen").c_str(),         &isSVgen);
      tree->Branch((name+"_isSVb").c_str(),           &isSVb);
      tree->Branch((name+"_isSVc").c_str(),           &isSVc);
      tree->Branch((name+"_isSVl").c_str(),           &isSVl);
      tree->Branch((name+"_isSVo").c_str(),           &isSVo);
      tree->Branch((name+"_isSVbg").c_str(),          &isSVbg);
      tree->Branch((name+"_isSVcg").c_str(),          &isSVcg);
      tree->Branch((name+"_nbsSV").c_str(),           &nbsSV);
      tree->Branch((name+"_ncsSV").c_str(),           &ncsSV);
      tree->Branch((name+"_nlsSV").c_str(),           &nlsSV);
      tree->Branch((name+"_ngsSV").c_str(),           &ngsSV);
      tree->Branch((name+"_nothersSV").c_str(),       &nothersSV);
      tree->Branch((name+"_isMatchedtoGenSV").c_str(),&isMatchedtoGenSV);         
      tree->Branch((name+"_matchedGenIsLastCopyBeforeFSR").c_str(),  &matchedGenIsLastCopyBeforeFSR);
      tree->Branch((name+"_matchedGenIsHardProcess").c_str(),        &matchedGenIsHardProcess);
      tree->Branch((name+"_matchedGenPtSV").c_str(),  &matchedGenPtSV);
      tree->Branch((name+"_matchedGenEtaSV").c_str(), &matchedGenEtaSV);
      tree->Branch((name+"_matchedGenMassSV").c_str(),&matchedGenMassSV);
      tree->Branch((name+"_matchedGenPhiSV").c_str(), &matchedGenPhiSV);
      tree->Branch((name+"_matchedGenMomSV").c_str(), &matchedGenMomSV);
      tree->Branch((name+"_matchedGenMindRSV").c_str(),&matchedGenMindRSV);
      tree->Branch((name+"_matchedGenEnergySV").c_str(),   &matchedGenEnergySV);
      tree->Branch((name+"_matchedGendRSV").c_str(),  &matchedGendRSV);
      tree->Branch((name+"_trkDeltaRSV").c_str(), &trkDeltaRSV);
      tree->Branch((name+"_trkPtRelSV").c_str(), &trkPtRelSV);
      tree->Branch((name+"_trkEtaSV").c_str(), &trkEtaSV);
      tree->Branch((name+"_trkEtaRelSV").c_str(), &trkEtaRelSV);
      tree->Branch((name+"_trkPParSV").c_str(), &trkPParSV);
      tree->Branch((name+"_trkPtRatioSV").c_str(), &trkPtRatioSV);
      tree->Branch((name+"_trkPParRatioSV").c_str(), &trkPParRatioSV);
      tree->Branch((name+"_trkSip2dValSV").c_str(), &trkSip2dValSV);
      tree->Branch((name+"_trkSip2dSigSV").c_str(), &trkSip2dSigSV);
      tree->Branch((name+"_trkSip3dValSV").c_str(), &trkSip3dValSV);
      tree->Branch((name+"_trkSip3dSigSV").c_str(), &trkSip3dSigSV);
      tree->Branch((name+"_trkSVDistValSV").c_str(), &trkSVDistValSV);
      tree->Branch((name+"_trkSVDistSigSV").c_str(), &trkSVDistSigSV);
    }
};
