import FWCore.ParameterSet.Config as cms

makeNtuples = cms.EDAnalyzer('KUNtuplizer',
    #genParts          = cms.InputTag("packedGenParticles"),
    genParts          = cms.InputTag("prunedGenParticles"),    
    vertices          = cms.InputTag("offlineSlimmedPrimaryVertices"),
    secVertices       = cms.InputTag("slimmedSecondaryVertices"),
    ndofPV            = cms.int32(4),
    zPV               = cms.double(24),
    rhoPV             = cms.double(2),
    ptMaxSV           = cms.double(20.),
    dlenSigSV         = cms.double(4),
    d2dSV             = cms.double(3),
    cosPdotVSV        = cms.double(0.98),
    ndauSV            = cms.int32(2),
    jetdRSV           = cms.double(0.4),
    #ak4ptmax          = cms.double(30),
    genPartdRSV       = cms.double(0.4),
    puInfo            = cms.InputTag("slimmedAddPileupInfo"),
    electrons         = cms.InputTag("slimmedElectrons"),
    muons             = cms.InputTag("slimmedMuons"),
    photons           = cms.InputTag("slimmedPhotons"),
    beamSpot          = cms.InputTag("offlineBeamSpot"),
    conversion        = cms.InputTag("reducedEgamma", "reducedConversions", "PAT"),
    packedPFCands     = cms.InputTag("packedPFCandidates"),
    genJets           = cms.InputTag("slimmedGenJets"), 
    rho               = cms.InputTag("fixedGridRhoFastjetAll"), 
    jets              = cms.InputTag("slimmedJets"),
    jetsPuppi         = cms.InputTag("slimmedJetsPuppi"),
    jetsAk8           = cms.InputTag("slimmedJetsAK8"),
    mets              = cms.InputTag("slimmedMETs"),
    metsPuppi         = cms.InputTag("slimmedMETsPuppi"),
    metNoHF           = cms.InputTag("slimmedMETsNoHF"),
    subjetsAk8        = cms.InputTag("slimmedJetsAK8PFCHSSoftDropPacked:SubJets"),
    triggerResults    = cms.InputTag("TriggerResults"),
    triggerSummary    = cms.InputTag("hltTriggerSummaryAOD"),
    hltElectronFilter = cms.InputTag("hltL1sL1Mu3p5EG12ORL1MuOpenEG12L3Filtered8")
)
